/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAuditoriaFretesRouteImport } from './routes/_authenticated/auditoria-fretes'
import { Route as AuthenticatedBorderosRouteImport } from './routes/_authenticated/borderos'
import { Route as AuthenticatedCapturaCteRouteImport } from './routes/_authenticated/captura-cte'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedConfiguracoesFretesRouteImport } from './routes/_authenticated/configuracoes-fretes'
import { Route as AuthenticatedCtesRouteImport } from './routes/_authenticated/ctes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedFretistasRouteImport } from './routes/_authenticated/fretistas'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedMinhasRotasRouteImport } from './routes/_authenticated/minhas-rotas'
import { Route as AuthenticatedPagamentoFretesRouteImport } from './routes/_authenticated/pagamento-fretes'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedSugestaoRotasRouteImport } from './routes/_authenticated/sugestao-rotas'
import { Route as AuthenticatedTabelasFreteRouteImport } from './routes/_authenticated/tabelas-frete'
import { Route as AuthenticatedTransportadorasRouteImport } from './routes/_authenticated/transportadoras'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedCtesCteIdRouteImport } from './routes/_authenticated/ctes.$cteId'
import { Route as AuthenticatedNfesChaveRouteImport } from './routes/_authenticated/nfes.$chave'
import { Route as AuthenticatedPedidosIndexRouteImport } from './routes/_authenticated/pedidos.index'
import { Route as AuthenticatedPedidosOrderIdRouteImport } from './routes/_authenticated/pedidos.$orderId'
import { Route as AuthenticatedRotasIndexRouteImport } from './routes/_authenticated/rotas.index'
import { Route as AuthenticatedRotasRouteIdRouteImport } from './routes/_authenticated/rotas.$routeId'
import { Route as ApiPublicHooksCteComandosRouteImport } from './routes/api/public/hooks/cte-comandos'
import { Route as ApiPublicHooksErpSyncRouteImport } from './routes/api/public/hooks/erp-sync'
import { Route as ApiPublicHooksIngestCteRouteImport } from './routes/api/public/hooks/ingest-cte'
import { Route as ApiPublicHooksIngestNfeRouteImport } from './routes/api/public/hooks/ingest-nfe'
import { Route as ApiPublicHooksNfePendentesRouteImport } from './routes/api/public/hooks/nfe-pendentes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditoriaFretesRoute =
  AuthenticatedAuditoriaFretesRouteImport.update({
    id: '/auditoria-fretes',
    path: '/auditoria-fretes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBorderosRoute = AuthenticatedBorderosRouteImport.update({
  id: '/borderos',
  path: '/borderos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCapturaCteRoute = AuthenticatedCapturaCteRouteImport.update({
  id: '/captura-cte',
  path: '/captura-cte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesFretesRoute =
  AuthenticatedConfiguracoesFretesRouteImport.update({
    id: '/configuracoes-fretes',
    path: '/configuracoes-fretes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCtesRoute = AuthenticatedCtesRouteImport.update({
  id: '/ctes',
  path: '/ctes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFretistasRoute = AuthenticatedFretistasRouteImport.update({
  id: '/fretistas',
  path: '/fretistas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhasRotasRoute =
  AuthenticatedMinhasRotasRouteImport.update({
    id: '/minhas-rotas',
    path: '/minhas-rotas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPagamentoFretesRoute =
  AuthenticatedPagamentoFretesRouteImport.update({
    id: '/pagamento-fretes',
    path: '/pagamento-fretes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSugestaoRotasRoute =
  AuthenticatedSugestaoRotasRouteImport.update({
    id: '/sugestao-rotas',
    path: '/sugestao-rotas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTabelasFreteRoute =
  AuthenticatedTabelasFreteRouteImport.update({
    id: '/tabelas-frete',
    path: '/tabelas-frete',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransportadorasRoute =
  AuthenticatedTransportadorasRouteImport.update({
    id: '/transportadoras',
    path: '/transportadoras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCtesCteIdRoute = AuthenticatedCtesCteIdRouteImport.update({
  id: '/$cteId',
  path: '/$cteId',
  getParentRoute: () => AuthenticatedCtesRoute,
} as any)
const AuthenticatedNfesChaveRoute = AuthenticatedNfesChaveRouteImport.update({
  id: '/nfes/$chave',
  path: '/nfes/$chave',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosIndexRoute =
  AuthenticatedPedidosIndexRouteImport.update({
    id: '/pedidos/',
    path: '/pedidos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosOrderIdRoute =
  AuthenticatedPedidosOrderIdRouteImport.update({
    id: '/pedidos/$orderId',
    path: '/pedidos/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotasIndexRoute = AuthenticatedRotasIndexRouteImport.update({
  id: '/rotas/',
  path: '/rotas/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotasRouteIdRoute =
  AuthenticatedRotasRouteIdRouteImport.update({
    id: '/rotas/$routeId',
    path: '/rotas/$routeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksCteComandosRoute =
  ApiPublicHooksCteComandosRouteImport.update({
    id: '/api/public/hooks/cte-comandos',
    path: '/api/public/hooks/cte-comandos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksErpSyncRoute = ApiPublicHooksErpSyncRouteImport.update({
  id: '/api/public/hooks/erp-sync',
  path: '/api/public/hooks/erp-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIngestCteRoute = ApiPublicHooksIngestCteRouteImport.update({
  id: '/api/public/hooks/ingest-cte',
  path: '/api/public/hooks/ingest-cte',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIngestNfeRoute = ApiPublicHooksIngestNfeRouteImport.update({
  id: '/api/public/hooks/ingest-nfe',
  path: '/api/public/hooks/ingest-nfe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNfePendentesRoute =
  ApiPublicHooksNfePendentesRouteImport.update({
    id: '/api/public/hooks/nfe-pendentes',
    path: '/api/public/hooks/nfe-pendentes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auditoria-fretes': typeof AuthenticatedAuditoriaFretesRoute
  '/borderos': typeof AuthenticatedBorderosRoute
  '/captura-cte': typeof AuthenticatedCapturaCteRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/configuracoes-fretes': typeof AuthenticatedConfiguracoesFretesRoute
  '/ctes': typeof AuthenticatedCtesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/fretistas': typeof AuthenticatedFretistasRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/minhas-rotas': typeof AuthenticatedMinhasRotasRoute
  '/pagamento-fretes': typeof AuthenticatedPagamentoFretesRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/sugestao-rotas': typeof AuthenticatedSugestaoRotasRoute
  '/tabelas-frete': typeof AuthenticatedTabelasFreteRoute
  '/transportadoras': typeof AuthenticatedTransportadorasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/ctes/$cteId': typeof AuthenticatedCtesCteIdRoute
  '/nfes/$chave': typeof AuthenticatedNfesChaveRoute
  '/pedidos/$orderId': typeof AuthenticatedPedidosOrderIdRoute
  '/rotas/$routeId': typeof AuthenticatedRotasRouteIdRoute
  '/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/rotas/': typeof AuthenticatedRotasIndexRoute
  '/api/public/hooks/cte-comandos': typeof ApiPublicHooksCteComandosRoute
  '/api/public/hooks/erp-sync': typeof ApiPublicHooksErpSyncRoute
  '/api/public/hooks/ingest-cte': typeof ApiPublicHooksIngestCteRoute
  '/api/public/hooks/ingest-nfe': typeof ApiPublicHooksIngestNfeRoute
  '/api/public/hooks/nfe-pendentes': typeof ApiPublicHooksNfePendentesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auditoria-fretes': typeof AuthenticatedAuditoriaFretesRoute
  '/borderos': typeof AuthenticatedBorderosRoute
  '/captura-cte': typeof AuthenticatedCapturaCteRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/configuracoes-fretes': typeof AuthenticatedConfiguracoesFretesRoute
  '/ctes': typeof AuthenticatedCtesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/fretistas': typeof AuthenticatedFretistasRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/minhas-rotas': typeof AuthenticatedMinhasRotasRoute
  '/pagamento-fretes': typeof AuthenticatedPagamentoFretesRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/sugestao-rotas': typeof AuthenticatedSugestaoRotasRoute
  '/tabelas-frete': typeof AuthenticatedTabelasFreteRoute
  '/transportadoras': typeof AuthenticatedTransportadorasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/ctes/$cteId': typeof AuthenticatedCtesCteIdRoute
  '/nfes/$chave': typeof AuthenticatedNfesChaveRoute
  '/pedidos/$orderId': typeof AuthenticatedPedidosOrderIdRoute
  '/rotas/$routeId': typeof AuthenticatedRotasRouteIdRoute
  '/pedidos': typeof AuthenticatedPedidosIndexRoute
  '/rotas': typeof AuthenticatedRotasIndexRoute
  '/api/public/hooks/cte-comandos': typeof ApiPublicHooksCteComandosRoute
  '/api/public/hooks/erp-sync': typeof ApiPublicHooksErpSyncRoute
  '/api/public/hooks/ingest-cte': typeof ApiPublicHooksIngestCteRoute
  '/api/public/hooks/ingest-nfe': typeof ApiPublicHooksIngestNfeRoute
  '/api/public/hooks/nfe-pendentes': typeof ApiPublicHooksNfePendentesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/auditoria-fretes': typeof AuthenticatedAuditoriaFretesRoute
  '/_authenticated/borderos': typeof AuthenticatedBorderosRoute
  '/_authenticated/captura-cte': typeof AuthenticatedCapturaCteRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/configuracoes-fretes': typeof AuthenticatedConfiguracoesFretesRoute
  '/_authenticated/ctes': typeof AuthenticatedCtesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/fretistas': typeof AuthenticatedFretistasRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/minhas-rotas': typeof AuthenticatedMinhasRotasRoute
  '/_authenticated/pagamento-fretes': typeof AuthenticatedPagamentoFretesRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/sugestao-rotas': typeof AuthenticatedSugestaoRotasRoute
  '/_authenticated/tabelas-frete': typeof AuthenticatedTabelasFreteRoute
  '/_authenticated/transportadoras': typeof AuthenticatedTransportadorasRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/ctes/$cteId': typeof AuthenticatedCtesCteIdRoute
  '/_authenticated/nfes/$chave': typeof AuthenticatedNfesChaveRoute
  '/_authenticated/pedidos/$orderId': typeof AuthenticatedPedidosOrderIdRoute
  '/_authenticated/rotas/$routeId': typeof AuthenticatedRotasRouteIdRoute
  '/_authenticated/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/_authenticated/rotas/': typeof AuthenticatedRotasIndexRoute
  '/api/public/hooks/cte-comandos': typeof ApiPublicHooksCteComandosRoute
  '/api/public/hooks/erp-sync': typeof ApiPublicHooksErpSyncRoute
  '/api/public/hooks/ingest-cte': typeof ApiPublicHooksIngestCteRoute
  '/api/public/hooks/ingest-nfe': typeof ApiPublicHooksIngestNfeRoute
  '/api/public/hooks/nfe-pendentes': typeof ApiPublicHooksNfePendentesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auditoria-fretes'
    | '/borderos'
    | '/captura-cte'
    | '/clientes'
    | '/configuracoes'
    | '/configuracoes-fretes'
    | '/ctes'
    | '/dashboard'
    | '/empresas'
    | '/fretistas'
    | '/kanban'
    | '/minhas-rotas'
    | '/pagamento-fretes'
    | '/produtos'
    | '/sugestao-rotas'
    | '/tabelas-frete'
    | '/transportadoras'
    | '/usuarios'
    | '/ctes/$cteId'
    | '/nfes/$chave'
    | '/pedidos/$orderId'
    | '/rotas/$routeId'
    | '/pedidos/'
    | '/rotas/'
    | '/api/public/hooks/cte-comandos'
    | '/api/public/hooks/erp-sync'
    | '/api/public/hooks/ingest-cte'
    | '/api/public/hooks/ingest-nfe'
    | '/api/public/hooks/nfe-pendentes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auditoria-fretes'
    | '/borderos'
    | '/captura-cte'
    | '/clientes'
    | '/configuracoes'
    | '/configuracoes-fretes'
    | '/ctes'
    | '/dashboard'
    | '/empresas'
    | '/fretistas'
    | '/kanban'
    | '/minhas-rotas'
    | '/pagamento-fretes'
    | '/produtos'
    | '/sugestao-rotas'
    | '/tabelas-frete'
    | '/transportadoras'
    | '/usuarios'
    | '/ctes/$cteId'
    | '/nfes/$chave'
    | '/pedidos/$orderId'
    | '/rotas/$routeId'
    | '/pedidos'
    | '/rotas'
    | '/api/public/hooks/cte-comandos'
    | '/api/public/hooks/erp-sync'
    | '/api/public/hooks/ingest-cte'
    | '/api/public/hooks/ingest-nfe'
    | '/api/public/hooks/nfe-pendentes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/auditoria-fretes'
    | '/_authenticated/borderos'
    | '/_authenticated/captura-cte'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/configuracoes-fretes'
    | '/_authenticated/ctes'
    | '/_authenticated/dashboard'
    | '/_authenticated/empresas'
    | '/_authenticated/fretistas'
    | '/_authenticated/kanban'
    | '/_authenticated/minhas-rotas'
    | '/_authenticated/pagamento-fretes'
    | '/_authenticated/produtos'
    | '/_authenticated/sugestao-rotas'
    | '/_authenticated/tabelas-frete'
    | '/_authenticated/transportadoras'
    | '/_authenticated/usuarios'
    | '/_authenticated/ctes/$cteId'
    | '/_authenticated/nfes/$chave'
    | '/_authenticated/pedidos/$orderId'
    | '/_authenticated/rotas/$routeId'
    | '/_authenticated/pedidos/'
    | '/_authenticated/rotas/'
    | '/api/public/hooks/cte-comandos'
    | '/api/public/hooks/erp-sync'
    | '/api/public/hooks/ingest-cte'
    | '/api/public/hooks/ingest-nfe'
    | '/api/public/hooks/nfe-pendentes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksCteComandosRoute: typeof ApiPublicHooksCteComandosRoute
  ApiPublicHooksErpSyncRoute: typeof ApiPublicHooksErpSyncRoute
  ApiPublicHooksIngestCteRoute: typeof ApiPublicHooksIngestCteRoute
  ApiPublicHooksIngestNfeRoute: typeof ApiPublicHooksIngestNfeRoute
  ApiPublicHooksNfePendentesRoute: typeof ApiPublicHooksNfePendentesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/auditoria-fretes': {
      id: '/_authenticated/auditoria-fretes'
      path: '/auditoria-fretes'
      fullPath: '/auditoria-fretes'
      preLoaderRoute: typeof AuthenticatedAuditoriaFretesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/borderos': {
      id: '/_authenticated/borderos'
      path: '/borderos'
      fullPath: '/borderos'
      preLoaderRoute: typeof AuthenticatedBorderosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/captura-cte': {
      id: '/_authenticated/captura-cte'
      path: '/captura-cte'
      fullPath: '/captura-cte'
      preLoaderRoute: typeof AuthenticatedCapturaCteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes-fretes': {
      id: '/_authenticated/configuracoes-fretes'
      path: '/configuracoes-fretes'
      fullPath: '/configuracoes-fretes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesFretesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ctes': {
      id: '/_authenticated/ctes'
      path: '/ctes'
      fullPath: '/ctes'
      preLoaderRoute: typeof AuthenticatedCtesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fretistas': {
      id: '/_authenticated/fretistas'
      path: '/fretistas'
      fullPath: '/fretistas'
      preLoaderRoute: typeof AuthenticatedFretistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-rotas': {
      id: '/_authenticated/minhas-rotas'
      path: '/minhas-rotas'
      fullPath: '/minhas-rotas'
      preLoaderRoute: typeof AuthenticatedMinhasRotasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamento-fretes': {
      id: '/_authenticated/pagamento-fretes'
      path: '/pagamento-fretes'
      fullPath: '/pagamento-fretes'
      preLoaderRoute: typeof AuthenticatedPagamentoFretesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sugestao-rotas': {
      id: '/_authenticated/sugestao-rotas'
      path: '/sugestao-rotas'
      fullPath: '/sugestao-rotas'
      preLoaderRoute: typeof AuthenticatedSugestaoRotasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tabelas-frete': {
      id: '/_authenticated/tabelas-frete'
      path: '/tabelas-frete'
      fullPath: '/tabelas-frete'
      preLoaderRoute: typeof AuthenticatedTabelasFreteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transportadoras': {
      id: '/_authenticated/transportadoras'
      path: '/transportadoras'
      fullPath: '/transportadoras'
      preLoaderRoute: typeof AuthenticatedTransportadorasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ctes/$cteId': {
      id: '/_authenticated/ctes/$cteId'
      path: '/$cteId'
      fullPath: '/ctes/$cteId'
      preLoaderRoute: typeof AuthenticatedCtesCteIdRouteImport
      parentRoute: typeof AuthenticatedCtesRoute
    }
    '/_authenticated/nfes/$chave': {
      id: '/_authenticated/nfes/$chave'
      path: '/nfes/$chave'
      fullPath: '/nfes/$chave'
      preLoaderRoute: typeof AuthenticatedNfesChaveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/': {
      id: '/_authenticated/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof AuthenticatedPedidosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/$orderId': {
      id: '/_authenticated/pedidos/$orderId'
      path: '/pedidos/$orderId'
      fullPath: '/pedidos/$orderId'
      preLoaderRoute: typeof AuthenticatedPedidosOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotas/': {
      id: '/_authenticated/rotas/'
      path: '/rotas'
      fullPath: '/rotas/'
      preLoaderRoute: typeof AuthenticatedRotasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotas/$routeId': {
      id: '/_authenticated/rotas/$routeId'
      path: '/rotas/$routeId'
      fullPath: '/rotas/$routeId'
      preLoaderRoute: typeof AuthenticatedRotasRouteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/cte-comandos': {
      id: '/api/public/hooks/cte-comandos'
      path: '/api/public/hooks/cte-comandos'
      fullPath: '/api/public/hooks/cte-comandos'
      preLoaderRoute: typeof ApiPublicHooksCteComandosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/erp-sync': {
      id: '/api/public/hooks/erp-sync'
      path: '/api/public/hooks/erp-sync'
      fullPath: '/api/public/hooks/erp-sync'
      preLoaderRoute: typeof ApiPublicHooksErpSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-cte': {
      id: '/api/public/hooks/ingest-cte'
      path: '/api/public/hooks/ingest-cte'
      fullPath: '/api/public/hooks/ingest-cte'
      preLoaderRoute: typeof ApiPublicHooksIngestCteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-nfe': {
      id: '/api/public/hooks/ingest-nfe'
      path: '/api/public/hooks/ingest-nfe'
      fullPath: '/api/public/hooks/ingest-nfe'
      preLoaderRoute: typeof ApiPublicHooksIngestNfeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/nfe-pendentes': {
      id: '/api/public/hooks/nfe-pendentes'
      path: '/api/public/hooks/nfe-pendentes'
      fullPath: '/api/public/hooks/nfe-pendentes'
      preLoaderRoute: typeof ApiPublicHooksNfePendentesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCtesRouteChildren {
  AuthenticatedCtesCteIdRoute: typeof AuthenticatedCtesCteIdRoute
}

const AuthenticatedCtesRouteChildren: AuthenticatedCtesRouteChildren = {
  AuthenticatedCtesCteIdRoute: AuthenticatedCtesCteIdRoute,
}

const AuthenticatedCtesRouteWithChildren =
  AuthenticatedCtesRoute._addFileChildren(AuthenticatedCtesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditoriaFretesRoute: typeof AuthenticatedAuditoriaFretesRoute
  AuthenticatedBorderosRoute: typeof AuthenticatedBorderosRoute
  AuthenticatedCapturaCteRoute: typeof AuthenticatedCapturaCteRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConfiguracoesFretesRoute: typeof AuthenticatedConfiguracoesFretesRoute
  AuthenticatedCtesRoute: typeof AuthenticatedCtesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedFretistasRoute: typeof AuthenticatedFretistasRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedMinhasRotasRoute: typeof AuthenticatedMinhasRotasRoute
  AuthenticatedPagamentoFretesRoute: typeof AuthenticatedPagamentoFretesRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedSugestaoRotasRoute: typeof AuthenticatedSugestaoRotasRoute
  AuthenticatedTabelasFreteRoute: typeof AuthenticatedTabelasFreteRoute
  AuthenticatedTransportadorasRoute: typeof AuthenticatedTransportadorasRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedNfesChaveRoute: typeof AuthenticatedNfesChaveRoute
  AuthenticatedPedidosOrderIdRoute: typeof AuthenticatedPedidosOrderIdRoute
  AuthenticatedRotasRouteIdRoute: typeof AuthenticatedRotasRouteIdRoute
  AuthenticatedPedidosIndexRoute: typeof AuthenticatedPedidosIndexRoute
  AuthenticatedRotasIndexRoute: typeof AuthenticatedRotasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditoriaFretesRoute: AuthenticatedAuditoriaFretesRoute,
  AuthenticatedBorderosRoute: AuthenticatedBorderosRoute,
  AuthenticatedCapturaCteRoute: AuthenticatedCapturaCteRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConfiguracoesFretesRoute: AuthenticatedConfiguracoesFretesRoute,
  AuthenticatedCtesRoute: AuthenticatedCtesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedFretistasRoute: AuthenticatedFretistasRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedMinhasRotasRoute: AuthenticatedMinhasRotasRoute,
  AuthenticatedPagamentoFretesRoute: AuthenticatedPagamentoFretesRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedSugestaoRotasRoute: AuthenticatedSugestaoRotasRoute,
  AuthenticatedTabelasFreteRoute: AuthenticatedTabelasFreteRoute,
  AuthenticatedTransportadorasRoute: AuthenticatedTransportadorasRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedNfesChaveRoute: AuthenticatedNfesChaveRoute,
  AuthenticatedPedidosOrderIdRoute: AuthenticatedPedidosOrderIdRoute,
  AuthenticatedRotasRouteIdRoute: AuthenticatedRotasRouteIdRoute,
  AuthenticatedPedidosIndexRoute: AuthenticatedPedidosIndexRoute,
  AuthenticatedRotasIndexRoute: AuthenticatedRotasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksCteComandosRoute: ApiPublicHooksCteComandosRoute,
  ApiPublicHooksErpSyncRoute: ApiPublicHooksErpSyncRoute,
  ApiPublicHooksIngestCteRoute: ApiPublicHooksIngestCteRoute,
  ApiPublicHooksIngestNfeRoute: ApiPublicHooksIngestNfeRoute,
  ApiPublicHooksNfePendentesRoute: ApiPublicHooksNfePendentesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
