/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedFretistasRouteImport } from './routes/_authenticated/fretistas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedBorderosRouteImport } from './routes/_authenticated/borderos'
import { Route as AuthenticatedRotasIndexRouteImport } from './routes/_authenticated/rotas.index'
import { Route as AuthenticatedPedidosIndexRouteImport } from './routes/_authenticated/pedidos.index'
import { Route as AuthenticatedRotasRouteIdRouteImport } from './routes/_authenticated/rotas.$routeId'
import { Route as AuthenticatedPedidosOrderIdRouteImport } from './routes/_authenticated/pedidos.$orderId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFretistasRoute = AuthenticatedFretistasRouteImport.update({
  id: '/fretistas',
  path: '/fretistas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBorderosRoute = AuthenticatedBorderosRouteImport.update({
  id: '/borderos',
  path: '/borderos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotasIndexRoute = AuthenticatedRotasIndexRouteImport.update({
  id: '/rotas/',
  path: '/rotas/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosIndexRoute =
  AuthenticatedPedidosIndexRouteImport.update({
    id: '/pedidos/',
    path: '/pedidos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotasRouteIdRoute =
  AuthenticatedRotasRouteIdRouteImport.update({
    id: '/rotas/$routeId',
    path: '/rotas/$routeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosOrderIdRoute =
  AuthenticatedPedidosOrderIdRouteImport.update({
    id: '/pedidos/$orderId',
    path: '/pedidos/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/borderos': typeof AuthenticatedBorderosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fretistas': typeof AuthenticatedFretistasRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/pedidos/$orderId': typeof AuthenticatedPedidosOrderIdRoute
  '/rotas/$routeId': typeof AuthenticatedRotasRouteIdRoute
  '/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/rotas/': typeof AuthenticatedRotasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/borderos': typeof AuthenticatedBorderosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fretistas': typeof AuthenticatedFretistasRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/pedidos/$orderId': typeof AuthenticatedPedidosOrderIdRoute
  '/rotas/$routeId': typeof AuthenticatedRotasRouteIdRoute
  '/pedidos': typeof AuthenticatedPedidosIndexRoute
  '/rotas': typeof AuthenticatedRotasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/borderos': typeof AuthenticatedBorderosRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fretistas': typeof AuthenticatedFretistasRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/pedidos/$orderId': typeof AuthenticatedPedidosOrderIdRoute
  '/_authenticated/rotas/$routeId': typeof AuthenticatedRotasRouteIdRoute
  '/_authenticated/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/_authenticated/rotas/': typeof AuthenticatedRotasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/borderos'
    | '/clientes'
    | '/dashboard'
    | '/fretistas'
    | '/kanban'
    | '/produtos'
    | '/pedidos/$orderId'
    | '/rotas/$routeId'
    | '/pedidos/'
    | '/rotas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/borderos'
    | '/clientes'
    | '/dashboard'
    | '/fretistas'
    | '/kanban'
    | '/produtos'
    | '/pedidos/$orderId'
    | '/rotas/$routeId'
    | '/pedidos'
    | '/rotas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/borderos'
    | '/_authenticated/clientes'
    | '/_authenticated/dashboard'
    | '/_authenticated/fretistas'
    | '/_authenticated/kanban'
    | '/_authenticated/produtos'
    | '/_authenticated/pedidos/$orderId'
    | '/_authenticated/rotas/$routeId'
    | '/_authenticated/pedidos/'
    | '/_authenticated/rotas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fretistas': {
      id: '/_authenticated/fretistas'
      path: '/fretistas'
      fullPath: '/fretistas'
      preLoaderRoute: typeof AuthenticatedFretistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/borderos': {
      id: '/_authenticated/borderos'
      path: '/borderos'
      fullPath: '/borderos'
      preLoaderRoute: typeof AuthenticatedBorderosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotas/': {
      id: '/_authenticated/rotas/'
      path: '/rotas'
      fullPath: '/rotas/'
      preLoaderRoute: typeof AuthenticatedRotasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/': {
      id: '/_authenticated/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof AuthenticatedPedidosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotas/$routeId': {
      id: '/_authenticated/rotas/$routeId'
      path: '/rotas/$routeId'
      fullPath: '/rotas/$routeId'
      preLoaderRoute: typeof AuthenticatedRotasRouteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/$orderId': {
      id: '/_authenticated/pedidos/$orderId'
      path: '/pedidos/$orderId'
      fullPath: '/pedidos/$orderId'
      preLoaderRoute: typeof AuthenticatedPedidosOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBorderosRoute: typeof AuthenticatedBorderosRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFretistasRoute: typeof AuthenticatedFretistasRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedPedidosOrderIdRoute: typeof AuthenticatedPedidosOrderIdRoute
  AuthenticatedRotasRouteIdRoute: typeof AuthenticatedRotasRouteIdRoute
  AuthenticatedPedidosIndexRoute: typeof AuthenticatedPedidosIndexRoute
  AuthenticatedRotasIndexRoute: typeof AuthenticatedRotasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBorderosRoute: AuthenticatedBorderosRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFretistasRoute: AuthenticatedFretistasRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedPedidosOrderIdRoute: AuthenticatedPedidosOrderIdRoute,
  AuthenticatedRotasRouteIdRoute: AuthenticatedRotasRouteIdRoute,
  AuthenticatedPedidosIndexRoute: AuthenticatedPedidosIndexRoute,
  AuthenticatedRotasIndexRoute: AuthenticatedRotasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
